import { useEffect, useMemo, useState } from 'react'
import {
  ArrowRight,
  BedDouble,
  Bot,
  Brain,
  CheckCircle2,
  Flame,
  Footprints,
  HeartPulse,
  Minus,
  Play,
  Sparkles,
  Square,
  TrendingDown,
  TrendingUp,
  X,
} from 'lucide-react'
import MainLayout from '../components/MainLayout'
import { useApp } from '../context/AppContext'
import { getAISummary, syncStravaActivities } from '../services/api'

const STRINGS = {
  English: {
    aiHealthSummary: 'AI Health Summary',
    dailyUpdate: 'Daily Update',
    weeklyPulse: 'Your Weekly Pulse',
    keyInsights: 'Key Insights',
    viewAll: 'View All',
    basedOnSummary: 'Based on your summary',
    generatedBy: 'Generated by AI based on your data',
    listen: 'Listen',
    stop: 'Stop',
    sleep: 'Sleep',
    steps: 'Steps',
    heartRate: 'Avg Heart Rate',
    calories: 'Calories',
    healthScore: 'Health Score',
    wellness: 'Wellness',
    status: 'Status',
    trend: 'Trend',
    noSummary: 'No health summary available yet.',
    loadingTitle: 'Generating AI Summary...',
    loadingSubtitle: 'This may take a few seconds',
    failedTitle: 'Failed to load AI Summary',
    retry: 'Retry',
    showingOffline: 'Showing cached data (Offline)',
    lightCardio: 'Light Cardio',
    lightCardioDesc: 'Try a 15-min walk to boost recovery.',
    mindfulness: 'Mindfulness',
    mindfulnessDesc: 'Deep breathing before bed.',
  },
  Hindi: {
    aiHealthSummary: 'AI स्वास्थ्य सारांश',
    dailyUpdate: 'दैनिक अपडेट',
    weeklyPulse: 'आपका साप्ताहिक पल्स',
    keyInsights: 'मुख्य अंतर्दृष्टि',
    viewAll: 'सभी देखें',
    basedOnSummary: 'आपके सारांश के आधार पर',
    generatedBy: 'आपके डेटा के आधार पर AI द्वारा जेनरेट किया गया',
    listen: 'सुनें',
    stop: 'रोकें',
    sleep: 'नींद',
    steps: 'कदम',
    heartRate: 'औसत हृदय गति',
    calories: 'कैलोरी',
    healthScore: 'स्वास्थ्य स्कोर',
    wellness: 'कल्याण',
    status: 'स्थिति',
    trend: 'रुझान',
    noSummary: 'अभी तक कोई स्वास्थ्य सारांश उपलब्ध नहीं है।',
    loadingTitle: 'AI सारांश जनरेट हो रहा है...',
    loadingSubtitle: 'इसमें कुछ सेकंड लग सकते हैं',
    failedTitle: 'AI सारांश लोड नहीं हुआ',
    retry: 'फिर कोशिश करें',
    showingOffline: 'कैश डेटा दिखाया जा रहा है (ऑफलाइन)',
    lightCardio: 'हल्का कार्डियो',
    lightCardioDesc: 'रिकवरी बढ़ाने के लिए 15 मिनट की सैर करें।',
    mindfulness: 'माइंडफुलनेस',
    mindfulnessDesc: 'सोने से पहले गहरी सांस लें।',
  },
  Marathi: {
    aiHealthSummary: 'AI आरोग्य सारांश',
    dailyUpdate: 'दैनिक अपडेट',
    weeklyPulse: 'तुमचा साप्ताहिक पल्स',
    keyInsights: 'मुख्य अंतर्दृष्टी',
    viewAll: 'सर्व पहा',
    basedOnSummary: 'तुमच्या सारांशावर आधारित',
    generatedBy: 'तुमच्या डेटावर आधारित AI द्वारे व्युत्पन्न',
    listen: 'ऐका',
    stop: 'थांबा',
    sleep: 'झोप',
    steps: 'पावले',
    heartRate: 'सरासरी हृदय गती',
    calories: 'कॅलरीज',
    healthScore: 'आरोग्य स्कोअर',
    wellness: 'आरोग्य स्थिती',
    status: 'स्थिती',
    trend: 'ट्रेंड',
    noSummary: 'अद्याप कोणताही आरोग्य सारांश उपलब्ध नाही.',
    loadingTitle: 'AI सारांश तयार होत आहे...',
    loadingSubtitle: 'यासाठी काही सेकंद लागू शकतात',
    failedTitle: 'AI सारांश लोड झाला नाही',
    retry: 'पुन्हा प्रयत्न करा',
    showingOffline: 'कॅश डेटा दाखवत आहे (ऑफलाइन)',
    lightCardio: 'हलका कार्डिओ',
    lightCardioDesc: 'रिकव्हरी वाढवण्यासाठी 15 मिनिटांची चाल करा।',
    mindfulness: 'माइंडफुलनेस',
    mindfulnessDesc: 'झोपण्यापूर्वी खोल श्वास घ्या।',
  },
}

function deriveSleepChange(avgSleep) {
  const parsed = Number(avgSleep)
  if (!Number.isFinite(parsed) || parsed <= 0) return '+0hrs'

  const baseline = 8
  const delta = Number((parsed - baseline).toFixed(1))
  if (Math.abs(delta) < 0.1) return '+0hrs'

  return `${delta > 0 ? '+' : ''}${delta}hrs`
}

function formatUpdatedTime(iso) {
  if (!iso) return 'UPDATED JUST NOW'
  const diff = Date.now() - new Date(iso).getTime()
  const minutes = Math.floor(diff / 60000)

  if (minutes < 1) return 'UPDATED JUST NOW'
  if (minutes < 60) return `UPDATED ${minutes}M AGO`

  const hours = Math.floor(minutes / 60)
  if (hours < 24) return `UPDATED ${hours}H AGO`

  return `UPDATED ${Math.floor(hours / 24)}D AGO`
}

function getTrendMeta(trend) {
  if (trend === 'Positive') {
    return {
      icon: TrendingUp,
      iconClass: 'text-blue-600',
      bgClass: 'bg-blue-100 dark:bg-blue-900/30',
      badgeClass: 'bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30',
    }
  }
  if (trend === 'Negative') {
    return {
      icon: TrendingDown,
      iconClass: 'text-red-500',
      bgClass: 'bg-red-100 dark:bg-red-900/30',
      badgeClass: 'bg-red-100 text-red-600 dark:bg-red-900/30',
    }
  }
  return {
    icon: Minus,
    iconClass: 'text-slate-500',
    bgClass: 'bg-slate-100 dark:bg-slate-700',
    badgeClass: 'bg-slate-100 text-slate-600 dark:bg-slate-700 dark:text-slate-300',
  }
}

function getSleepInsightDetails(sleepChange) {
  if (sleepChange.startsWith('+')) {
    return {
      trend: 'Improving',
      trendClass: 'bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30',
      description:
        'Great! Your sleep duration has improved compared to last week. Keep maintaining a consistent sleep schedule.',
    }
  }

  if (sleepChange.startsWith('-')) {
    return {
      trend: 'Declining',
      trendClass: 'bg-red-100 text-red-600 dark:bg-red-900/30',
      description:
        'Your sleep duration has decreased. Try going to bed 30 minutes earlier tonight.',
    }
  }

  return {
    trend: 'Stable',
    trendClass: 'bg-slate-100 text-slate-600 dark:bg-slate-700 dark:text-slate-300',
    description:
      'Your sleep pattern is stable. Consider optimizing your sleep quality with a consistent bedtime routine.',
  }
}

function getStepsInsightDetails(steps) {
  if (steps >= 10000) {
    return {
      trend: 'Excellent',
      trendClass: 'bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30',
      description:
        "Excellent! You've exceeded the recommended daily step goal. Your cardiovascular health is benefiting.",
    }
  }

  if (steps >= 7000) {
    return {
      trend: 'Good',
      trendClass: 'bg-amber-100 text-amber-700 dark:bg-amber-900/30',
      description:
        "Good progress! You're close to the 10,000 step goal. Try adding a short walk after meals.",
    }
  }

  return {
    trend: 'Needs Improvement',
    trendClass: 'bg-red-100 text-red-600 dark:bg-red-900/30',
    description:
      'Consider increasing your daily activity. Start with a goal of 7,000 steps and work your way up.',
  }
}

function getStatusInsightDetails(status) {
  if (status === 'Recovered') {
    return {
      trend: status,
      trendClass: 'bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30',
      description:
        "Your body has fully recovered. You're ready for your regular activities and exercise routine.",
    }
  }

  if (status === 'Improving') {
    return {
      trend: status,
      trendClass: 'bg-amber-100 text-amber-700 dark:bg-amber-900/30',
      description:
        'Your health metrics are trending positively. Continue your current healthy habits.',
    }
  }

  return {
    trend: status,
    trendClass: 'bg-red-100 text-red-600 dark:bg-red-900/30',
    description:
      'Some health indicators need attention. Consider consulting with a healthcare professional.',
  }
}

function getTrendInsightDetails(trend) {
  if (trend === 'Positive') {
    return {
      trend,
      trendClass: 'bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30',
      description:
        'Your overall health trajectory is improving. Your consistent efforts are paying off!',
    }
  }

  if (trend === 'Negative') {
    return {
      trend,
      trendClass: 'bg-red-100 text-red-600 dark:bg-red-900/30',
      description:
        'Your health metrics show a declining trend. Focus on sleep, hydration, and regular exercise.',
    }
  }

  return {
    trend,
    trendClass: 'bg-slate-100 text-slate-600 dark:bg-slate-700 dark:text-slate-300',
    description:
      'Your health metrics are stable. Consider setting new goals to continue improving.',
  }
}

function getHeartRateInsightDetails(avgHeartRate) {
  if (avgHeartRate >= 60 && avgHeartRate <= 85) {
    return {
      trend: 'Healthy',
      trendClass: 'bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30',
      description:
        'Your average heart rate is in a healthy range. Keep up your balanced routine.',
    }
  }

  if (avgHeartRate > 0 && avgHeartRate <= 100) {
    return {
      trend: 'Monitor',
      trendClass: 'bg-amber-100 text-amber-700 dark:bg-amber-900/30',
      description:
        'Your average heart rate is slightly elevated. Improve hydration and include recovery time.',
    }
  }

  return {
    trend: 'Attention',
    trendClass: 'bg-red-100 text-red-600 dark:bg-red-900/30',
    description:
      'Your heart rate trend needs attention. Consider reducing intensity and consulting a professional if needed.',
  }
}

function getCaloriesInsightDetails(calories) {
  if (calories >= 550) {
    return {
      trend: 'Active',
      trendClass: 'bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30',
      description:
        'Great calorie burn this week. Your activity level supports weight and cardiovascular goals.',
    }
  }

  if (calories >= 350) {
    return {
      trend: 'Moderate',
      trendClass: 'bg-amber-100 text-amber-700 dark:bg-amber-900/30',
      description:
        'You are moderately active. Add one extra walk or workout session for a stronger weekly burn.',
    }
  }

  return {
    trend: 'Low',
    trendClass: 'bg-red-100 text-red-600 dark:bg-red-900/30',
    description:
      'Your calorie burn is low this week. Increase movement with short but frequent activity blocks.',
  }
}

function getHealthScoreInsightDetails(score) {
  if (score >= 85) {
    return {
      trend: 'Excellent',
      trendClass: 'bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30',
      description:
        'Your health score is excellent. Maintain consistency in sleep, activity, and recovery.',
    }
  }

  if (score >= 70) {
    return {
      trend: 'Good',
      trendClass: 'bg-brand/15 text-brand',
      description:
        'Your health score is good. A small increase in daily movement can move you to the next tier.',
    }
  }

  if (score >= 50) {
    return {
      trend: 'Fair',
      trendClass: 'bg-amber-100 text-amber-700 dark:bg-amber-900/30',
      description:
        'Your health score is fair. Focus on sleep regularity and hitting your daily step target.',
    }
  }

  return {
    trend: 'Needs Attention',
    trendClass: 'bg-red-100 text-red-600 dark:bg-red-900/30',
    description:
      'Your health score indicates a recovery gap. Prioritize rest, hydration, and low-intensity movement.',
  }
}

function getWellnessInsightDetails(wellness) {
  const normalized = String(wellness || '').toLowerCase()

  if (normalized.includes('excellent')) {
    return {
      trend: 'Excellent',
      trendClass: 'bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30',
      description:
        'Your overall wellness is excellent and stable. Continue your current healthy rhythm.',
    }
  }

  if (normalized.includes('good')) {
    return {
      trend: 'Good',
      trendClass: 'bg-brand/15 text-brand',
      description:
        'Your overall wellness is good. A little more consistency can unlock excellent status.',
    }
  }

  if (normalized.includes('fair')) {
    return {
      trend: 'Fair',
      trendClass: 'bg-amber-100 text-amber-700 dark:bg-amber-900/30',
      description:
        'Your wellness is fair. Improve sleep timing and add daily walking for better balance.',
    }
  }

  return {
    trend: 'Needs Attention',
    trendClass: 'bg-red-100 text-red-600 dark:bg-red-900/30',
    description:
      'Your wellness needs attention this week. Focus on recovery, hydration, and gradual activity.',
  }
}

function RecommendationIcon({ title }) {
  const normalized = String(title || '').toLowerCase()

  if (normalized.includes('walk') || normalized.includes('cardio') || normalized.includes('run')) {
    return <Footprints size={20} />
  }
  if (normalized.includes('mindful') || normalized.includes('meditat') || normalized.includes('breath')) {
    return <Brain size={20} />
  }
  if (normalized.includes('sleep') || normalized.includes('rest')) {
    return <BedDouble size={20} />
  }
  if (normalized.includes('heart') || normalized.includes('pulse')) {
    return <HeartPulse size={20} />
  }

  return <Sparkles size={20} />
}

function recommendationTone(index) {
  const tones = [
    'bg-blue-100 text-blue-600 dark:bg-blue-900/30',
    'bg-violet-100 text-violet-600 dark:bg-violet-900/30',
    'bg-emerald-100 text-emerald-600 dark:bg-emerald-900/30',
    'bg-orange-100 text-orange-600 dark:bg-orange-900/30',
    'bg-pink-100 text-pink-600 dark:bg-pink-900/30',
  ]
  return tones[index % tones.length]
}

function defaultRecommendations(text) {
  return [
    { title: text.lightCardio, description: text.lightCardioDesc },
    { title: text.mindfulness, description: text.mindfulnessDesc },
  ]
}

function buildSpeechText(
  language,
  summaryText,
  sleepAdvice,
  steps,
  sleepChange,
  status,
  trend,
  avgHeartRate,
  caloriesBurned,
  healthScore,
  overallWellness,
  text,
) {
  if (language === 'Hindi') {
    return `आपका साप्ताहिक स्वास्थ्य सारांश। ${text.steps} ${steps}. ${text.sleep} ${sleepChange}. ${text.heartRate} ${avgHeartRate} बीपीएम. ${text.calories} ${caloriesBurned}. ${text.healthScore} ${healthScore}. ${text.wellness} ${overallWellness}. ${text.status} ${status}. ${text.trend} ${trend}. ${sleepAdvice}`
  }

  if (language === 'Marathi') {
    return `तुमचा साप्ताहिक आरोग्य सारांश. ${text.steps} ${steps}. ${text.sleep} ${sleepChange}. ${text.heartRate} ${avgHeartRate} BPM. ${text.calories} ${caloriesBurned}. ${text.healthScore} ${healthScore}. ${text.wellness} ${overallWellness}. ${text.status} ${status}. ${text.trend} ${trend}. ${sleepAdvice}`
  }

  return `${summaryText}. ${text.steps} ${steps}. ${text.sleep} ${sleepChange}. ${text.heartRate} ${avgHeartRate} bpm. ${text.calories} ${caloriesBurned}. ${text.healthScore} ${healthScore}. ${text.wellness} ${overallWellness}. ${sleepAdvice}`
}

export default function AISummaryPage() {
  const { language } = useApp()
  const text = STRINGS[language] || STRINGS.English

  const [loading, setLoading] = useState(true)
  const [isOffline, setIsOffline] = useState(false)
  const [error, setError] = useState('')
  const [isSpeaking, setIsSpeaking] = useState(false)
  const [showInsightsModal, setShowInsightsModal] = useState(false)

  const [summaryText, setSummaryText] = useState('')
  const [sleepAdvice, setSleepAdvice] = useState('')
  const [updatedAt, setUpdatedAt] = useState('UPDATED JUST NOW')
  const [sleepChange, setSleepChange] = useState('+0hrs')
  const [steps, setSteps] = useState(0)
  const [avgHeartRate, setAvgHeartRate] = useState(0)
  const [caloriesBurned, setCaloriesBurned] = useState(0)
  const [healthScore, setHealthScore] = useState(0)
  const [overallWellness, setOverallWellness] = useState('Good')
  const [status, setStatus] = useState('Recovered')
  const [trend, setTrend] = useState('Positive')
  const [recommendations, setRecommendations] = useState([])

  useEffect(() => {
    fetchSummary()

    return () => {
      if (typeof window !== 'undefined' && window.speechSynthesis) {
        window.speechSynthesis.cancel()
      }
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  useEffect(() => {
    if (typeof document === 'undefined') return undefined

    const previousOverflow = document.body.style.overflow

    if (showInsightsModal) {
      document.body.style.overflow = 'hidden'
    } else {
      document.body.style.overflow = previousOverflow || ''
    }

    return () => {
      document.body.style.overflow = previousOverflow
    }
  }, [showInsightsModal])

  async function fetchSummary() {
    setLoading(true)
    setError('')

    await syncStravaActivities()
    const result = await getAISummary({ forceRefresh: true })

    if (!result.success || !result.data) {
      setLoading(false)
      setError(result.message || 'Failed to load AI summary')
      return
    }

    const data = result.data
    const pulse = data.weeklyPulse || {}
    const insights = data.keyInsights || {}
    const avgSleep = Number(insights.avgSleep || 0)

    setIsOffline(result.cached === true)
    setSummaryText(pulse.summaryText || '')
    setSleepAdvice(pulse.sleepAdvice || '')
    setUpdatedAt(formatUpdatedTime(pulse.updatedAt))

    setSleepChange(String(insights.sleepChange || deriveSleepChange(avgSleep)))
    setSteps(Number(insights.steps || 0))
    setAvgHeartRate(Number(insights.avgHeartRate || 0))
    setCaloriesBurned(Number(insights.caloriesBurned || 0))
    setHealthScore(Number(insights.healthScore || 0))
    setOverallWellness(String(insights.overallWellness || 'Good'))
    setStatus(insights.status || 'Recovered')
    setTrend(insights.trend || 'Positive')
    setRecommendations(
      Array.isArray(data.recommendations)
        ? data.recommendations.filter((item) => item?.title || item?.description)
        : [],
    )

    setLoading(false)
  }

  function speakSummary() {
    if (typeof window === 'undefined' || !window.speechSynthesis) return

    const synthesis = window.speechSynthesis

    if (isSpeaking) {
      synthesis.cancel()
      setIsSpeaking(false)
      return
    }

    const speechText = buildSpeechText(
      language,
      summaryText || text.noSummary,
      sleepAdvice,
      steps,
      sleepChange,
      status,
      trend,
      avgHeartRate,
      caloriesBurned,
      healthScore,
      overallWellness,
      text,
    )

    const utterance = new SpeechSynthesisUtterance(speechText)
    utterance.rate = 0.9
    utterance.pitch = 1.1
    utterance.lang = language === 'Hindi' ? 'hi-IN' : language === 'Marathi' ? 'mr-IN' : 'en-US'

    const preferredVoice = synthesis
      .getVoices()
      .find((voice) => voice.lang?.startsWith(utterance.lang.split('-')[0]))
    if (preferredVoice) {
      utterance.voice = preferredVoice
    }

    utterance.onend = () => setIsSpeaking(false)
    utterance.onerror = () => setIsSpeaking(false)

    synthesis.cancel()
    synthesis.speak(utterance)
    setIsSpeaking(true)
  }

  const trendMeta = useMemo(() => getTrendMeta(trend), [trend])

  const insightChips = useMemo(
    () => [
      {
        key: 'sleep',
        label: text.sleep,
        value: sleepChange,
        icon: BedDouble,
        iconClass: 'text-indigo-600',
        bgClass: 'bg-indigo-100 dark:bg-indigo-900/30',
      },
      {
        key: 'steps',
        label: text.steps,
        value: steps.toLocaleString(),
        icon: Footprints,
        iconClass: 'text-orange-600',
        bgClass: 'bg-orange-100 dark:bg-orange-900/30',
      },
      {
        key: 'heartRate',
        label: text.heartRate,
        value: `${avgHeartRate} bpm`,
        icon: HeartPulse,
        iconClass: 'text-rose-600',
        bgClass: 'bg-rose-100 dark:bg-rose-900/30',
      },
      {
        key: 'calories',
        label: text.calories,
        value: `${Math.round(caloriesBurned).toLocaleString()} kcal`,
        icon: Flame,
        iconClass: 'text-orange-600',
        bgClass: 'bg-orange-100 dark:bg-orange-900/30',
      },
      {
        key: 'healthScore',
        label: text.healthScore,
        value: `${Math.round(healthScore)}/100`,
        icon: Sparkles,
        iconClass: 'text-violet-600',
        bgClass: 'bg-violet-100 dark:bg-violet-900/30',
      },
      {
        key: 'wellness',
        label: text.wellness,
        value: overallWellness,
        icon: CheckCircle2,
        iconClass: 'text-emerald-600',
        bgClass: 'bg-emerald-100 dark:bg-emerald-900/30',
      },
      {
        key: 'status',
        label: text.status,
        value: status,
        icon: CheckCircle2,
        iconClass: status === 'Needs Attention' ? 'text-red-500' : 'text-emerald-600',
        bgClass: status === 'Needs Attention' ? 'bg-red-100 dark:bg-red-900/30' : 'bg-emerald-100 dark:bg-emerald-900/30',
      },
      {
        key: 'trend',
        label: text.trend,
        value: trend,
        icon: trendMeta.icon,
        iconClass: trendMeta.iconClass,
        bgClass: trendMeta.bgClass,
      },
    ],
    [
      text,
      sleepChange,
      steps,
      avgHeartRate,
      caloriesBurned,
      healthScore,
      overallWellness,
      status,
      trend,
      trendMeta,
    ],
  )

  const detailedInsights = useMemo(() => {
    const sleepDetails = getSleepInsightDetails(sleepChange)
    const stepsDetails = getStepsInsightDetails(steps)
    const heartRateDetails = getHeartRateInsightDetails(avgHeartRate)
    const caloriesDetails = getCaloriesInsightDetails(caloriesBurned)
    const healthScoreDetails = getHealthScoreInsightDetails(healthScore)
    const wellnessDetails = getWellnessInsightDetails(overallWellness)
    const statusDetails = getStatusInsightDetails(status)
    const trendDetails = getTrendInsightDetails(trend)

    return [
      {
        key: 'sleep',
        label: text.sleep,
        value: sleepChange,
        icon: BedDouble,
        iconClass: 'text-indigo-600',
        bgClass: 'bg-indigo-100 dark:bg-indigo-900/30',
        trend: sleepDetails.trend,
        trendClass: sleepDetails.trendClass,
        description: sleepDetails.description,
      },
      {
        key: 'steps',
        label: text.steps,
        value: steps.toLocaleString(),
        icon: Footprints,
        iconClass: 'text-orange-600',
        bgClass: 'bg-orange-100 dark:bg-orange-900/30',
        trend: stepsDetails.trend,
        trendClass: stepsDetails.trendClass,
        description: stepsDetails.description,
      },
      {
        key: 'heartRate',
        label: text.heartRate,
        value: `${avgHeartRate} bpm`,
        icon: HeartPulse,
        iconClass: 'text-rose-600',
        bgClass: 'bg-rose-100 dark:bg-rose-900/30',
        trend: heartRateDetails.trend,
        trendClass: heartRateDetails.trendClass,
        description: heartRateDetails.description,
      },
      {
        key: 'calories',
        label: text.calories,
        value: `${Math.round(caloriesBurned).toLocaleString()} kcal`,
        icon: Flame,
        iconClass: 'text-orange-600',
        bgClass: 'bg-orange-100 dark:bg-orange-900/30',
        trend: caloriesDetails.trend,
        trendClass: caloriesDetails.trendClass,
        description: caloriesDetails.description,
      },
      {
        key: 'healthScore',
        label: text.healthScore,
        value: `${Math.round(healthScore)}/100`,
        icon: Sparkles,
        iconClass: 'text-violet-600',
        bgClass: 'bg-violet-100 dark:bg-violet-900/30',
        trend: healthScoreDetails.trend,
        trendClass: healthScoreDetails.trendClass,
        description: healthScoreDetails.description,
      },
      {
        key: 'wellness',
        label: text.wellness,
        value: overallWellness,
        icon: CheckCircle2,
        iconClass: 'text-emerald-600',
        bgClass: 'bg-emerald-100 dark:bg-emerald-900/30',
        trend: wellnessDetails.trend,
        trendClass: wellnessDetails.trendClass,
        description: wellnessDetails.description,
      },
      {
        key: 'status',
        label: text.status,
        value: status,
        icon: CheckCircle2,
        iconClass: status === 'Needs Attention' ? 'text-red-500' : 'text-emerald-600',
        bgClass: status === 'Needs Attention' ? 'bg-red-100 dark:bg-red-900/30' : 'bg-emerald-100 dark:bg-emerald-900/30',
        trend: statusDetails.trend,
        trendClass: statusDetails.trendClass,
        description: statusDetails.description,
      },
      {
        key: 'trend',
        label: text.trend,
        value: trend,
        icon: trendMeta.icon,
        iconClass: trendMeta.iconClass,
        bgClass: trendMeta.bgClass,
        trend: trendDetails.trend,
        trendClass: trendDetails.trendClass,
        description: trendDetails.description,
      },
    ]
  }, [
    text,
    sleepChange,
    steps,
    avgHeartRate,
    caloriesBurned,
    healthScore,
    overallWellness,
    status,
    trend,
    trendMeta,
  ])

  const recommendationItems = recommendations.length
    ? recommendations
    : defaultRecommendations(text)

  return (
    <MainLayout title={text.aiHealthSummary} onRefresh={fetchSummary} headerMode="center">
      {isOffline ? (
        <div className="mt-2 rounded-xl bg-amber-100 px-3 py-2 text-xs font-semibold text-amber-700">
          {text.showingOffline}
        </div>
      ) : null}

      {loading ? (
        <div className="card mt-4 p-10 text-center">
          <div className="mx-auto h-9 w-9 animate-spin rounded-full border-4 border-brand border-t-transparent" />
          <p className="mt-4 text-sm font-semibold text-slate-600 dark:text-slate-200">{text.loadingTitle}</p>
          <p className="mt-1 text-xs text-appMuted">{text.loadingSubtitle}</p>
        </div>
      ) : error ? (
        <div className="card mt-4 space-y-3 p-6 text-center">
          <p className="text-lg font-bold text-red-500">{text.failedTitle}</p>
          <p className="text-sm text-slate-500">{error}</p>
          <button className="mx-auto rounded-xl bg-brand px-5 py-2 text-sm font-semibold text-white" onClick={fetchSummary}>
            {text.retry}
          </button>
        </div>
      ) : (
        <>
          <section className="relative mt-4 overflow-hidden rounded-[28px] border border-brand/10 bg-brand/10 p-6 shadow-card dark:bg-brand/15">
            <div className="pointer-events-none absolute -right-14 -top-14 h-48 w-48 rounded-full bg-brand/20" />

            <div className="relative">
              <div className="flex items-start justify-between gap-4">
                <span className="inline-flex rounded-full border border-brand/25 bg-white/75 px-3 py-1 text-[11px] font-bold uppercase tracking-[0.12em] text-brand dark:bg-slate-800/70">
                  {text.dailyUpdate}
                </span>
                <span className="inline-flex h-12 w-12 items-center justify-center rounded-2xl border border-white/60 bg-white text-brand shadow-sm dark:border-slate-700 dark:bg-slate-800">
                  <Bot size={24} />
                </span>
              </div>

              <h2 className="mt-5 text-3xl font-extrabold tracking-tight text-slate-900 dark:text-white">{text.weeklyPulse}</h2>
              <p className="mt-4 text-sm leading-7 text-slate-700 dark:text-slate-200">{summaryText || text.noSummary}</p>

              <div className="mt-4 rounded-xl border border-white/40 bg-white/70 p-4 dark:border-slate-700 dark:bg-slate-900/30">
                <div className="flex items-start gap-2">
                  <Sparkles size={16} className="mt-0.5 text-amber-500" />
                  <p className="text-sm leading-6 text-appMuted">{sleepAdvice}</p>
                </div>
              </div>

              <div className="mt-4 flex items-center justify-between gap-3">
                <button
                  className="inline-flex items-center gap-2 rounded-xl border border-brand/35 bg-white px-4 py-2 text-sm font-bold text-brand dark:bg-slate-800"
                  onClick={speakSummary}
                >
                  {isSpeaking ? <Square size={16} /> : <Play size={16} />}
                  {isSpeaking ? text.stop : text.listen}
                </button>
                <p className="text-[11px] font-semibold tracking-[0.1em] text-slate-400">{updatedAt}</p>
              </div>
            </div>
          </section>

          <section className="mt-6">
            <div className="mb-3 flex items-center justify-between px-1">
              <h3 className="text-lg font-bold text-slate-900 dark:text-white">{text.keyInsights}</h3>
              <button className="text-xs font-bold text-brand" onClick={() => setShowInsightsModal(true)}>
                {text.viewAll}
              </button>
            </div>

            <div className="-mx-1 overflow-x-auto px-1 pb-1">
              <div className="flex min-w-max gap-3">
                {insightChips.map((insight) => (
                  <InsightChip key={insight.key} insight={insight} />
                ))}
              </div>
            </div>
          </section>

          <section className="mt-6">
            <h3 className="mb-3 px-1 text-lg font-bold text-slate-900 dark:text-white">{text.basedOnSummary}</h3>
            <div className="space-y-3">
              {recommendationItems.map((item, index) => (
                <RecommendationCard key={`${item.title}-${index}`} item={item} index={index} />
              ))}
            </div>
          </section>

          <p className="flex items-center justify-center gap-2 py-6 text-center text-xs text-slate-400">
            <Sparkles size={14} />
            {text.generatedBy}
          </p>
        </>
      )}

      {showInsightsModal ? (
        <div className="fixed inset-0 z-40 flex items-end overflow-hidden bg-black/45 sm:items-center sm:justify-center sm:p-4">
          <div className="flex h-[80vh] w-full max-h-[80vh] flex-col overflow-hidden rounded-t-3xl bg-white dark:bg-slate-900 sm:h-[84vh] sm:max-h-[84vh] sm:max-w-2xl sm:rounded-3xl">
            <div className="flex-shrink-0 p-5 pb-0">
              <div className="mx-auto mb-4 h-1.5 w-10 rounded-full bg-slate-300 dark:bg-slate-700" />

              <div className="mb-4 flex items-center justify-between">
                <h4 className="text-xl font-bold text-slate-900 dark:text-white">{text.keyInsights}</h4>
                <button
                  className="inline-flex h-8 w-8 items-center justify-center rounded-full bg-slate-100 text-slate-500 dark:bg-slate-700 dark:text-slate-200"
                  onClick={() => setShowInsightsModal(false)}
                >
                  <X size={16} />
                </button>
              </div>
            </div>

            <div className="min-h-0 flex-1 overflow-y-auto px-5 pb-5">
              <div className="space-y-3">
                {detailedInsights.map((insight) => (
                  <DetailedInsightCard key={insight.key} insight={insight} />
                ))}
              </div>
            </div>
          </div>
        </div>
      ) : null}
    </MainLayout>
  )
}

function InsightChip({ insight }) {
  const Icon = insight.icon

  return (
    <div className="flex h-14 min-w-[170px] items-center gap-3 rounded-2xl border border-appStroke bg-white px-3 shadow-soft dark:border-slate-700 dark:bg-slate-800">
      <span className={`inline-flex h-9 w-9 items-center justify-center rounded-full ${insight.bgClass}`}>
        <Icon size={16} className={insight.iconClass} />
      </span>

      <div className="min-w-0">
        <p className="text-[10px] font-semibold uppercase tracking-[0.1em] text-appMuted">{insight.label}</p>
        <p className="truncate text-sm font-bold text-slate-900 dark:text-white">{insight.value}</p>
      </div>
    </div>
  )
}

function RecommendationCard({ item, index }) {
  return (
    <div className="card flex items-center gap-4 p-4">
      <span className={`inline-flex h-12 w-12 items-center justify-center rounded-2xl ${recommendationTone(index)}`}>
        <RecommendationIcon title={item.title} />
      </span>

      <div className="min-w-0 flex-1">
        <p className="truncate text-sm font-bold text-slate-900 dark:text-white">{item.title}</p>
        <p className="text-xs text-appMuted">{item.description}</p>
      </div>

      <span className="inline-flex h-9 w-9 items-center justify-center rounded-full bg-slate-100 text-slate-400 dark:bg-slate-700 dark:text-slate-300">
        <ArrowRight size={16} />
      </span>
    </div>
  )
}

function DetailedInsightCard({ insight }) {
  const Icon = insight.icon

  return (
    <div className="card rounded-2xl p-4">
      <div className="flex items-start gap-3">
        <span className={`inline-flex h-11 w-11 items-center justify-center rounded-xl ${insight.bgClass}`}>
          <Icon size={20} className={insight.iconClass} />
        </span>

        <div className="min-w-0 flex-1">
          <div className="flex flex-wrap items-center justify-between gap-2">
            <div>
              <p className="text-xs font-semibold uppercase tracking-[0.1em] text-appMuted">{insight.label}</p>
              <p className="mt-1 text-2xl font-bold text-slate-900 dark:text-white">{insight.value}</p>
            </div>
            <span className={`rounded-full px-3 py-1 text-xs font-semibold ${insight.trendClass}`}>{insight.trend}</span>
          </div>

          <div className="mt-3 rounded-xl bg-slate-50 p-3 dark:bg-slate-800">
            <div className="flex items-start gap-2">
              <Sparkles size={14} className="mt-0.5 text-amber-500" />
              <p className="text-sm leading-6 text-appMuted">{insight.description}</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
